wandb_version: 1

LR:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    python_version: 3.8.10
    start_time: 1660217878.188865
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.13.1
      8:
      - 5
layers:
  desc: null
  value:
  - LayersHyperParameters(layer_type='shepard', kernels_num=8, kernel_size=4, stride=1,
    padding='same')
  - LayersHyperParameters(layer_type='shepard', kernels_num=8, kernel_size=4, stride=1,
    padding='same')
  - LayersHyperParameters(layer_type='conv', kernels_num=128, kernel_size=9, stride=1,
    padding='same')
  - LayersHyperParameters(layer_type='conv', kernels_num=128, kernel_size=1, stride=1,
    padding='same')
  - LayersHyperParameters(layer_type='conv', kernels_num=3, kernel_size=8, stride=1,
    padding='same')
